### ISSUE TITLE
Playing a file just throws an error

### ISSUE THREAD

**Issue by essenbee** [mobiletechtracker/NetCoreAudio#3]
Attempting to play a .wav file (or .mp3 file), just throws an error code 266:

![image](https://user-images.githubusercontent.com/7979108/57569359-eb145d80-73eb-11e9-960e-39afeba4f3fc.png)

Windows 10 (latest) with .net core 2.2.
Looks like the error code is this: "Unknown problem while loading the specified device driver." Error 266 is MCIERR_CANNOT_LOAD_DRIVER.

**Comment by Ashurek85** [comment]
I have the same issue.

Windows 10 and Net Core 2.2

![image](https://user-images.githubusercontent.com/45046196/59674796-4d6b3580-91c4-11e9-9ca7-3b23ead6051f.png)

**Comment by anuphunt** [comment]
Same issue.

**Comment by fiodarsazanavets** [comment]
Thank you guys for your feedback.

The issue was observed on certain Windows machines, while the library worked fine on other machines. The fix has been applied and version 1.5.0 has now been released.
