### ISSUE TITLE
Error when play .wav and .mp3

### ISSUE THREAD

**Issue by Doughboy02** [mobiletechtracker/NetCoreAudio#5]
I get an error whenever trying to run the line
`Player.Play(filePath).GetAwaiter().GetResult();`

Error
`Error executing MCI command 'Status C:\Users\Panda\source\repos\TextToSpeechApi\TextToSpeechApi\bin\Debug\netcoreapp2.1\Voices\testing sound.mp3 Length'. Error code: 310. Message: Specify a device or driver name that is less than 79 characters.`

Wasn't sure if this was the same error that has already been posted considering the Error code is different...

**Comment by MortenChristiansen** [comment]
Have you tried using a relative path?

**Comment by fiodarsazanavets** [comment]
On Windows, there is a hard limit on the number of characters you can use in the path or audio device alias in the media interface. As suggested, please use a relative path.

**Comment by fiodarsazanavets** [comment]
Closing since this issue is caused by the limitation of Windows media interface and not the library itself.
