### ISSUE TITLE
Feature Request: Disable the console output

### ISSUE THREAD

**Issue by smekonen** [mobiletechtracker/NetCoreAudio#7]
It would be nice if there was a way to configure the library to not write debug logs to the console for small console applications. Otherwise a great project.

**Comment by fiodarsazanavets** [comment]
Hi. The library itself is not outputting any console logs. The console application that comes with the repo is there for purely demo and test purposes.

The main part of the repo is the class library represented by NetCoreAudio project, which is also published on NuGet. Other than some exceptions, which are handled by the application that uses the library, there isn't any code inside of it that produces any logs.

However, there may be console output produced by the underlying OS-specific utilities that the library uses. It might depend on the setup of the host machine. Therefore, please provide the information on how to replicate it.

**Comment by smekonen** [comment]
Hello, thanks for your response. I was using the NuGet package. Here is one of the logs I got:
`Playing WAVE 'tones/audiocheck.net_sin_277.18Hz_-3dBFS_1s.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono`

I wasn't able to reproduce it with another console project. And moving the last one to a new project seems to have fixed the problem. It must have been something weird on my end.
